%---- program user interface interpolasi ----


% --- warna dasar --
% 185 216 164 -- hijau 1 rgb
% 91 193 147  -- hijau 2 rgb
% 9 50 31     -- hujai 3 rgb
% 170 236 209 -- hijau 4 rgb
% 0 0 0       -- hitam
% 1 1 1 - putih
%0.725 0.847 0.643  -- hijau 1
%0.357 0.757 0.576  -- hijau 2
%0.035 0.196 0.122  -- hijau 3
%0.667 0.925 0.82   -- hijau 4

%Main Frame Interfare
win= figure(...
    'color',[0.667 0.925 0.82],...
    'units','characters',...
    'resize','off',...
    'position',[40 5 170 45],...
    'numbertitle','off',...
    'name','board utama',...
    'menubar','none',...
    'windowstyle','normal');
%header
header = uicontrol('Parent',win,...
    'Backgroundcolor',[0.725 0.847 0.643],...
    'units','characters',...
    'position',[0 40 171 5],...
    'style','text');
header1 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.357 0.757 0.576],...
    'units','characters',...
    'position',[0 40 33 5],...
    'style','text');
header2 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.035 0.196 0.122],...
    'units','characters',...
    'position',[0 40 17 5],...
    'style','text');
header3 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.035 0.196 0.122],...
    'units','characters',...
    'position',[137 40 33 5],...
    'style','text');
header4 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.357 0.757 0.576],...
    'units','characters',...
    'position',[130 40 17 5],...
    'style','text');
judulutama = uicontrol('Parent',win,...
    'Backgroundcolor',[0.725 0.847 0.643],...
    'style','text',...
    'string','Interpolation Graphic Plotting Program',...
    'units','characters',...
    'position',[57 40 55 5],...
    'fontsize',20);
%footer
footer = uicontrol('Parent',win,...
    'Backgroundcolor',[0.725 0.847 0.643],...
    'units','characters',...
    'position',[0 0 171 5],...
    'style','text');
footer11 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.357 0.757 0.576],...
    'units','characters',...
    'position',[0 0 110 5],...
    'style','text');
footer9 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.035 0.196 0.122],...
    'units','characters',...
    'position',[0 0 99 5],...
    'style','text');
footer8 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.357 0.757 0.576],...
    'units','characters',...
    'position',[0 0 88 5],...
    'style','text');
footer7 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.035 0.196 0.122],...
    'units','characters',...
    'position',[0 0 77 5],...
    'style','text');
footer6 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.357 0.757 0.576],...
    'units','characters',...
    'position',[0 0 66 5],...
    'style','text');
footer5 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.035 0.196 0.122],...
    'units','characters',...
    'position',[0 0 55 5],...
    'style','text');
footer4 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.357 0.757 0.576],...
    'units','characters',...
    'position',[0 0 44 5],...
    'style','text');
footer3 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.035 0.196 0.122],...
    'units','characters',...
    'position',[0 0 33 5],...
    'style','text');
footer1 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.357 0.757 0.576],...
    'units','characters',...
    'position',[0 0 22 5],...
    'style','text');
footer2 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.035 0.196 0.122],...
    'units','characters',...
    'position',[0 0 11 5],...
    'style','text');
judulFooter = uicontrol('Parent',win,...
    'Backgroundcolor',[0.725 0.847 0.643],...
    'style','text',...
    'string','Nurdiansyah',...
    'units','characters',...
    'position',[121 1.7 55 3],...
    'fontsize',15);
judulFooter1 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.725 0.847 0.643],...
    'style','text',...
    'string','Fisika - IPB University',...
    'units','characters',...
    'position',[117 0 55 3],...
    'fontsize',15);
 

%----MAIN PROGRAM---
%label main program
label1 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.667 0.925 0.82],...
    'style','text',...
    'string','Masukan Data',...
    'units','characters',...
    'position',[3 35 30 2],...
    'fontsize',13);
label2 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.667 0.925 0.82],...
    'style','text',...
    'string','Metode',...
    'units','characters',...
    'position',[-2 30 30 2],...
    'fontsize',13);
%Push Botton
tombolBrowse = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[31 33 20 2],...
    'string','Browse...',...
    'callback','LoadData');
TombolRun = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[7 20 44 2.5],...
    'string','Run Interpolasi',...
    'fontsize',9,...
    'callback','Run');
TombolGambar = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[7 8 44 2.5],...
    'string','Info Developer',...
    'fontsize',9,...
    'callback','gambar');
TombolReset = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[7 16 44 2.5],...
    'string','Reset Grafik',...
    'fontsize',9,...
    'callback','Resetgrafik');
tombolTampilData = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[7 12 44 2.5],...
    'string','Menampikan Data ',...
    'fontsize',9,...
    'callback','TampilData');


%kolomisian
data = uicontrol('Parent',win,...
    'style','edit',...
    'units','characters',...
    'position',[7 33 22 2],...
    'enable','off');
orde = uicontrol('Parent',win,...
    'style','edit',...
    'units','characters',...
    'position',[18 24 33 2],...
    'visible','off',...
    'enable','on');
judulOrde= uicontrol('Parent',win,...
    'Backgroundcolor',[0.667 0.925 0.82],...
    'style','text',...
    'string','Orde',...
    'units','characters',...
    'position',[7 23 11 3],...
    'visible','off',...
    'fontsize',13);
menu_metode = uicontrol('Parent',win,...
    'style','popupmenu',...
    'units','characters',...
    'position',[7 28 44 2],...
    'fontsize',11,...
    'callback','visible',...
    'string','Linear|Nearest Neighbour|Polynomial|Cubic Spline|All Analytical');

%keterangan all variance
ket1 = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','text',...
    'string','keterangan',...
    'units','characters',...
    'position',[0 0 33 5],...
    'visible','off',...
    'fontsize',7);
ket2 = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','text',...
    'string','linier',...
    'units','characters',...
    'position',[0 0 9 1],...
    'visible','off',...
    'fontsize',7);
ket3 = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','text',...
    'string','nearrest',...
    'units','characters',...
    'position',[0 1 9 1],...
    'visible','off',...
    'fontsize',7);
ket4 = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','text',...
    'string','polynomial',...
    'units','characters',...
    'position',[0 2 9 1],...
    'visible','off',...
    'fontsize',7);
ket5 = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','text',...
    'string','spline',...
    'units','characters',...
    'position',[0 3 9 1],...
    'visible','off',...
    'fontsize',7);
ket6 = uicontrol('Parent',win,...
    'Backgroundcolor',[1 0 0],...
    'style','text',...
    'units','characters',...
    'position',[11 3 9 1],...
    'visible','off',...
    'fontsize',7);
ket7 = uicontrol('Parent',win,...
    'Backgroundcolor',[0 0 1],...
    'style','text',...
    'units','characters',...
    'position',[11 2 9 1],...
    'visible','off',...
    'fontsize',7);
ket8 = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 0],...
    'style','text',...
    'units','characters',...
    'position',[11 0 9 1],...
    'visible','off',...
    'fontsize',7);
ket9 = uicontrol('Parent',win,...
    'Backgroundcolor',[0.667 0.925 0.82],...
    'style','text',...
    'units','characters',...
    'position',[11 1 9 1],...
    'visible','off',...
    'fontsize',7);

%grafik
grafik= axes('Parent',win,...
    'units','characters',...
    'position',[59 7.7 107 29]);

%--------------------------------------------------------------------
tempatfile='';
namafile='';

